
services:

  eshop.catalogservice.api:
    build:
      context: .
      dockerfile: EShop.CatalogService.API/Dockerfile
    container_name: catalogservice
    ports:
      - "50001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__CatalogDb: "Server=sqlserver;Database=Catalog;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
    networks:
      - eshop-network
    depends_on:
    - sqlserver

  eshop.cartservice.api:
    build:
      context: .
      dockerfile: EShop.CartService.API/Dockerfile
    container_name: cartservice
    ports:
      - "50003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Redis: "redis:6379"
    networks:
      - eshop-network

  eshop.orderservice.api:
    build:
      context: .
      dockerfile: EShop.OrderService.API/Dockerfile
    container_name: orderservice
    ports:
      - "50002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__Redis: "redis:6379"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=Orders;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
    networks:
      - eshop-network
    depends_on:
     - sqlserver


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: eshop-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrongPassword123!"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - eshop-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    networks:
      - eshop-network


networks:
  eshop-network:

volumes:
  sql_data:
  redis_data: