version: "3.9"

services:

  eshop.catalogservice.api:
    build:
      context: .
      dockerfile: EShop.CatalogService.API/Dockerfile
    container_name: catalogservice
    ports:
      - "50001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=CatalogDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  eshop.orderservice.api:
    build:
      context: .
      dockerfile: EShop.OrderService.API/Dockerfile
    container_name: orderservice
    ports:
      - "50002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=OrderDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Password123"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
